#!/usr/bin/env perl

use strict;
use warnings;

use Config::Grammar;
use Getopt::Std;
use File::Copy;
use PriceChart;
use Template;


my %args;
getopts("v", \%args);

$| = 1 if ($args{v});

my $cfg = get_config();
my $dbh = get_dbh($cfg->{"general"});

my $http_cfg = $cfg->{"http"};
my $work_dir =  $http_cfg->{"chroot"} . $http_cfg->{"htdocs"};
print "info: work dir: $work_dir\n" if ($args{v});

my $config = {
	INTERPOLATE => 1,
	POST_CHOMP => 1,
	EVAL_PERL => 1,
	INCLUDE_PATH => $work_dir,
	OUTPUT_PATH => $work_dir
};
my $template = Template->new($config);

my $query = "select count(distinct manufacturer) from products";
my ($m) = $dbh->selectrow_array($query);

$query = "select count(part_num) from products";
my ($p) = $dbh->selectrow_array($query);

$query = "select count(distinct vendor) from prices";
my ($v) = $dbh->selectrow_array($query);

my $time = time - (7 * 24 * 60 * 60);
$query = "select count(part_num) from products where first_seen > ?";
my ($n) = $dbh->selectrow_array($query, undef, $time);

print "info: $m manufacturers, $p products ($n new), $v vendors\n" if ($args{v});
my $vars = {
	num_vendors => $v,
	num_manufacturers => $m,
	num_products => $p,
	new_products => $n
};

$template->process("index.tt2", $vars, "index.html")
	|| die "template: " . $template->error() . "\n";

$dbh->disconnect();
