#!/usr/bin/env perl

use strict;
use warnings;

use Config::Grammar;
use Getopt::Std;
use File::Copy;
use PriceChart;
use Template;


my %args;
getopts("v", \%args);

$| = 1 if ($args{v});

my $cfg = get_config();
my $dbh = get_dbh($cfg->{"general"});

my $work_dir =  $cfg->{"http"}{"chroot"} . $cfg->{"http"}{"htdocs"};
print "info: work dir: $work_dir\n" if ($args{v});

my $config = {
	INTERPOLATE => 1,
	POST_CHOMP => 1,
	EVAL_PERL => 1,
	INCLUDE_PATH => $work_dir,
	OUTPUT_PATH => $work_dir
};
my $template = Template->new($config);

my $query = "select count(distinct manufacturer) from products";
my ($m) = $dbh->selectrow_array($query);

$query = "select count(part_num) from products";
my ($p) = $dbh->selectrow_array($query);

$query = "select count(distinct vendor) from prices";
my ($v) = $dbh->selectrow_array($query);

my $time = time - (7 * 24 * 60 * 60);
$query = "select description from products where first_seen > $time";
my $new_products = $dbh->selectall_arrayref($query);

my $n = @$new_products;
print "info: $m manufacturers, $p products ($n new), $v vendors\n" if ($args{v});
my $vars = {
	num_vendors => $v,
	num_manufacturers => $m,
	num_products => $p,
	num_new => $n,
	new_products => $new_products
};

$template->process("index.tt2", $vars, "index.html")
	|| die "template: " . $template->error() . "\n";

$dbh->disconnect();
